/**
 * Integration tests — taskdag × llm-dag-generator cross-package wiring.
 *
 * Tests that DAGs generated by llm-dag-generator (fallback heuristic mode)
 * can be validated, executed, and replanned by the taskdag engine, covering
 * the full generate → validate → execute → fail → replan workflow.
 */

import { beforeEach, describe, expect, test } from "bun:test"

// llm-dag-generator
import { DAGGenerator, LLMDAGGenerator, createLLMDAGGenerator } from "../../llm-dag-generator/src/index"
import type { Capability } from "../../llm-dag-generator/src/index"

// taskdag
import {
  allSucceeded,
  estimateDAGCost,
  getReadyNodes,
  getTransitiveDependents,
  isComplete,
  markNodeFailed,
  replaceSubtree,
  validateDAG,
} from "../src/index"
import type { DAG, DAGNode } from "../src/index"

// ── Helpers ────────────────────────────────────────────────────────────────

const SAMPLE_CAPABILITIES: Capability[] = [
  {
    capability_id: "read_file",
    name: "Read File",
    risk_level: 0,
    tags: ["filesystem", "read"],
    success_rate: 0.98,
    description: "Read contents of a file from disk",
  },
  {
    capability_id: "analyze_code",
    name: "Analyze Code",
    risk_level: 0,
    tags: ["analysis", "code"],
    success_rate: 0.9,
    description: "Analyze code structure and patterns",
  },
  {
    capability_id: "write_file",
    name: "Write File",
    risk_level: 1,
    tags: ["filesystem", "write"],
    success_rate: 0.95,
    description: "Write content to a file on disk",
  },
  {
    capability_id: "run_tests",
    name: "Run Tests",
    risk_level: 1,
    tags: ["testing", "verify"],
    success_rate: 0.85,
    description: "Execute test suite and report results",
  },
  {
    capability_id: "deploy",
    name: "Deploy Application",
    risk_level: 2,
    tags: ["deployment", "production"],
    success_rate: 0.8,
    description: "Deploy application to production environment",
  },
  {
    capability_id: "rollback",
    name: "Rollback Deployment",
    risk_level: 2,
    tags: ["deployment", "rollback"],
    success_rate: 0.92,
    description: "Rollback a failed deployment",
  },
]

/** Build a valid linear 3-node DAG: n1 -> n2 -> n3 */
function createValidLinearDAG(): DAG {
  return {
    version: 1,
    nodes: [
      {
        node_id: "n1",
        capability_id: "read_file",
        inputs: { path: "src/index.ts" },
        dependencies: [],
        risk_level: 0,
        estimated_tokens: 100,
        estimated_duration_ms: 5000,
        status: "pending",
      },
      {
        node_id: "n2",
        capability_id: "analyze_code",
        inputs: { path: "src/index.ts" },
        dependencies: ["n1"],
        risk_level: 0,
        estimated_tokens: 150,
        estimated_duration_ms: 8000,
        status: "pending",
      },
      {
        node_id: "n3",
        capability_id: "write_file",
        inputs: { path: "src/patched.ts" },
        dependencies: ["n2"],
        risk_level: 1,
        estimated_tokens: 200,
        estimated_duration_ms: 5000,
        status: "pending",
      },
    ],
    edges: [
      ["n1", "n2"],
      ["n2", "n3"],
    ],
    metadata: {
      goal: "read and patch a file",
      strategy: "STAGED",
      replan_count: 0,
      created_at: Date.now(),
    },
  }
}

/** Build a valid diamond DAG: n1 -> n2, n3 -> n4 */
function createValidDiamondDAG(): DAG {
  return {
    version: 1,
    nodes: [
      {
        node_id: "n1",
        capability_id: "read_file",
        inputs: {},
        dependencies: [],
        risk_level: 0,
        estimated_tokens: 100,
        estimated_duration_ms: 5000,
        status: "pending",
      },
      {
        node_id: "n2",
        capability_id: "analyze_code",
        inputs: {},
        dependencies: ["n1"],
        risk_level: 0,
        estimated_tokens: 100,
        estimated_duration_ms: 5000,
        status: "pending",
      },
      {
        node_id: "n3",
        capability_id: "run_tests",
        inputs: {},
        dependencies: ["n1"],
        risk_level: 1,
        estimated_tokens: 100,
        estimated_duration_ms: 5000,
        status: "pending",
      },
      {
        node_id: "n4",
        capability_id: "deploy",
        inputs: {},
        dependencies: ["n2", "n3"],
        risk_level: 2,
        estimated_tokens: 100,
        estimated_duration_ms: 5000,
        status: "pending",
      },
    ],
    edges: [
      ["n1", "n2"],
      ["n1", "n3"],
      ["n2", "n4"],
      ["n3", "n4"],
    ],
    metadata: {
      goal: "deploy after analysis and tests",
      strategy: "STAGED",
      replan_count: 0,
      created_at: Date.now(),
    },
  }
}

function createReplacementNodes(parentId: string, prefix: string, count: number): DAGNode[] {
  const nodes: DAGNode[] = []
  for (let i = 0; i < count; i++) {
    const nodeId = `${prefix}_${i}`
    nodes.push({
      node_id: nodeId,
      capability_id: SAMPLE_CAPABILITIES[i % SAMPLE_CAPABILITIES.length]!.capability_id,
      inputs: {},
      dependencies: i === 0 ? [parentId] : [`${prefix}_${i - 1}`],
      risk_level: 1,
      estimated_tokens: 100,
      estimated_duration_ms: 5000,
      status: "pending",
    })
  }
  return nodes
}

// ── Tests ──────────────────────────────────────────────────────────────────

describe("Integration: DAGGenerator (llm-dag-generator) × taskdag engine", () => {
  let generator: DAGGenerator

  beforeEach(() => {
    generator = new DAGGenerator()
  })

  // ── Generate → Validate ──────────────────────────────────────────────

  test("fallback-generated DAG produces nodes with required fields", () => {
    const dag = generator.generateFallbackDAG("build a web app", SAMPLE_CAPABILITIES)
    expect(dag.nodes.length).toBeGreaterThan(0)
    expect(dag.nodes.length).toBeLessThanOrEqual(5)
    expect(dag.metadata.goal).toBe("build a web app")
    expect(dag.metadata.strategy).toBe("STAGED")

    // Each node has required taskdag-compatible fields
    for (const node of dag.nodes) {
      expect(node.node_id).toBeDefined()
      expect(node.capability_id).toBeDefined()
      expect(Array.isArray(node.dependencies)).toBe(true)
      expect(typeof node.risk_level).toBe("number")
      expect(node.status).toBe("pending")
    }
  })

  test("fallback DAG nodes reference valid capability_ids", () => {
    const dag = generator.generateFallbackDAG("process user data", SAMPLE_CAPABILITIES)
    const capIds = new Set(SAMPLE_CAPABILITIES.map((c) => c.capability_id))

    for (const node of dag.nodes) {
      expect(capIds.has(node.capability_id)).toBe(true)
    }
  })

  test("fallback DAG is a linear chain by dependencies", () => {
    // Use buildPrompt + generateFallbackDAG to verify the structure
    const prompt = generator.buildPrompt("test goal", SAMPLE_CAPABILITIES)
    expect(prompt).toContain("test goal")
    expect(prompt).toContain("Read File")
    expect(prompt).toContain("Deploy Application")

    const dag = generator.generateFallbackDAG("process user data", SAMPLE_CAPABILITIES)

    // In a linear chain, each node (except first) depends on the previous
    expect(dag.nodes.length).toBeGreaterThan(0)
    for (let i = 1; i < dag.nodes.length; i++) {
      const node = dag.nodes[i]!
      expect(node.dependencies.length).toBeGreaterThanOrEqual(1)
    }
  })

  // ── Valid DAG operations ─────────────────────────────────────────────

  test("valid linear DAG passes validation and produces execution order", () => {
    const dag = createValidLinearDAG()
    const result = validateDAG(dag)

    expect(result.valid).toBe(true)
    expect(result.executionOrder).toBeDefined()
    expect(result.executionOrder!.length).toBe(3)
    expect(result.executionOrder![0]).toBe("n1")
  })

  test("valid diamond DAG passes validation", () => {
    const dag = createValidDiamondDAG()
    const result = validateDAG(dag)

    expect(result.valid).toBe(true)
    expect(result.executionOrder!.length).toBe(4)
  })

  test("getReadyNodes returns correct nodes initially", () => {
    const dag = createValidLinearDAG()

    // Initially all nodes are pending
    const ready = getReadyNodes(dag)

    // Only n1 has no dependencies
    expect(ready.length).toBe(1)
    expect(ready[0]!.node_id).toBe("n1")
  })

  test("getReadyNodes in diamond DAG returns parallel-ready nodes", () => {
    const dag = createValidDiamondDAG()

    // Complete n1
    dag.nodes[0]!.status = "completed"

    // Now n2 and n3 should both be ready (parallel)
    const ready = getReadyNodes(dag)
    expect(ready.length).toBe(2)
    const readyIds = ready.map((n) => n.node_id).sort()
    expect(readyIds).toEqual(["n2", "n3"])
  })

  // ── DAG execution simulation ─────────────────────────────────────────

  test("sequential execution: completing nodes enables downstream nodes", () => {
    const dag = createValidLinearDAG()
    let currentDAG = structuredClone(dag)

    const completedOrder: string[] = []

    // Step 1: n1 is ready
    let ready = getReadyNodes(currentDAG)
    expect(ready.length).toBe(1)
    expect(ready[0]!.node_id).toBe("n1")
    currentDAG.nodes = currentDAG.nodes.map((n) =>
      n.node_id === "n1" ? { ...n, status: "completed" as const, output: "result-n1" } : n,
    )
    completedOrder.push("n1")

    // Step 2: n2 is ready
    ready = getReadyNodes(currentDAG)
    expect(ready.length).toBe(1)
    expect(ready[0]!.node_id).toBe("n2")
    currentDAG.nodes = currentDAG.nodes.map((n) =>
      n.node_id === "n2" ? { ...n, status: "completed" as const, output: "result-n2" } : n,
    )
    completedOrder.push("n2")

    // Step 3: n3 is ready
    ready = getReadyNodes(currentDAG)
    expect(ready.length).toBe(1)
    expect(ready[0]!.node_id).toBe("n3")
    currentDAG.nodes = currentDAG.nodes.map((n) =>
      n.node_id === "n3" ? { ...n, status: "completed" as const, output: "result-n3" } : n,
    )
    completedOrder.push("n3")

    expect(isComplete(currentDAG)).toBe(true)
    expect(allSucceeded(currentDAG)).toBe(true)
    expect(completedOrder).toEqual(["n1", "n2", "n3"])
  })

  test("DAG cost estimation aggregates across all nodes", () => {
    const dag = createValidLinearDAG()
    const cost = estimateDAGCost(dag)
    expect(cost.total_tokens).toBe(450) // 100 + 150 + 200
    expect(cost.total_duration_ms).toBe(18000) // 5000 + 8000 + 5000
  })

  // ── Failure cascading ────────────────────────────────────────────────

  test("markNodeFailed cascades to block downstream nodes", () => {
    const dag = createValidLinearDAG()
    // Fail n2: n2 fails, n3 blocked
    const updated = markNodeFailed(dag, "n2")

    const n2 = updated.nodes.find((n) => n.node_id === "n2")
    expect(n2!.status).toBe("failed")

    const n3 = updated.nodes.find((n) => n.node_id === "n3")
    expect(n3!.status).toBe("blocked")

    // n1 should be unaffected
    const n1 = updated.nodes.find((n) => n.node_id === "n1")
    expect(n1!.status).toBe("pending")
  })

  test("getTransitiveDependents finds all downstream nodes", () => {
    const dag = createValidLinearDAG()

    // From n1, all other nodes are downstream
    const fromN1 = getTransitiveDependents(dag, "n1")
    expect(fromN1.size).toBe(2)
    expect(fromN1.has("n2")).toBe(true)
    expect(fromN1.has("n3")).toBe(true)

    // From n2, only n3 is downstream
    const fromN2 = getTransitiveDependents(dag, "n2")
    expect(fromN2.size).toBe(1)
    expect(fromN2.has("n3")).toBe(true)
  })

  test("getTransitiveDependents with diamond DAG", () => {
    const dag = createValidDiamondDAG()

    // From n1: n2, n3, n4 are downstream
    const deps = getTransitiveDependents(dag, "n1")
    expect(deps.size).toBe(3)
    expect(deps.has("n2")).toBe(true)
    expect(deps.has("n3")).toBe(true)
    expect(deps.has("n4")).toBe(true)
  })

  // ── Replan workflow: fail → replace → resume ─────────────────────────

  test("replaceSubtree: failed subtree + replanned nodes form valid DAG", () => {
    const dag = createValidLinearDAG()

    // Complete n1
    dag.nodes[0]!.status = "completed"
    dag.nodes[0]!.output = "done"

    // Fail n2
    let workingDAG = markNodeFailed(dag, "n2")

    // Create replacement nodes starting from n1
    const replacementNodes = createReplacementNodes("n1", "repl", 2)
    const replannedDAG = replaceSubtree(workingDAG, "n2", replacementNodes)

    // Validate the replanned DAG
    const validation = validateDAG(replannedDAG)
    expect(validation.valid).toBe(true)

    // Completed n1 should remain
    const n1 = replannedDAG.nodes.find((n) => n.node_id === "n1")
    expect(n1).toBeDefined()
    expect(n1!.status).toBe("completed")

    // Replacement nodes should be present
    expect(replannedDAG.nodes.some((n) => n.node_id === "repl_0")).toBe(true)
    expect(replannedDAG.nodes.some((n) => n.node_id === "repl_1")).toBe(true)

    // Failed n2 should be removed from subtree
    expect(replannedDAG.nodes.some((n) => n.node_id === "n2")).toBe(false)

    // n3 should also be removed (was downstream of n2 in subtree)
    expect(replannedDAG.nodes.some((n) => n.node_id === "n3")).toBe(false)
  })

  test("replaceSubtree on diamond DAG preserves parallel branches", () => {
    const dag = createValidDiamondDAG()

    // Complete n1
    dag.nodes[0]!.status = "completed"

    // Fail n2 (one parallel branch)
    let workingDAG = markNodeFailed(dag, "n2")

    // n4 should be blocked (depends on n2 AND n3, and n2 failed)
    const n4After = workingDAG.nodes.find((n) => n.node_id === "n4")
    expect(n4After!.status).toBe("blocked")

    // Replace n2 subtree
    const replacementNodes = createReplacementNodes("n1", "fixed", 1)
    const replannedDAG = replaceSubtree(workingDAG, "n2", replacementNodes)

    expect(validateDAG(replannedDAG).valid).toBe(true)

    // n3 should still exist (other branch)
    expect(replannedDAG.nodes.some((n) => n.node_id === "n3")).toBe(true)
  })

  test("full generate → execute → fail → replan → resume workflow", () => {
    let taskDAG = createValidLinearDAG()

    // Step 1: complete n1
    taskDAG.nodes[0]!.status = "completed"
    taskDAG.nodes[0]!.output = "done"

    // Step 2: mark n2 as failed
    taskDAG = markNodeFailed(taskDAG, "n2")
    expect(taskDAG.nodes.some((n) => n.status === "failed")).toBe(true)

    // Step 3: replan — replace failed subtree
    const replacement = createReplacementNodes("n1", "r", 2)
    taskDAG = replaceSubtree(taskDAG, "n2", replacement)
    expect(validateDAG(taskDAG).valid).toBe(true)

    // Step 4: complete all remaining nodes
    let iteration = 0
    while (!isComplete(taskDAG) && iteration < 20) {
      const ready = getReadyNodes(taskDAG)
      if (ready.length === 0) break
      for (const node of ready) {
        taskDAG = {
          ...taskDAG,
          nodes: taskDAG.nodes.map((n) =>
            n.node_id === node.node_id ? { ...n, status: "completed" as const, output: `out-${node.node_id}` } : n,
          ),
        }
      }
      iteration++
    }

    expect(isComplete(taskDAG)).toBe(true)
    // Blocked n3 was removed in replan, remaining nodes are all completed
    const remaining = taskDAG.nodes.filter((n) => n.status === "completed")
    expect(remaining.length).toBe(3) // n1 + r_0 + r_1
  })
})

describe("Integration: LLMDAGGenerator with taskdag operations", () => {
  test("LLMDAGGenerator without provider produces valid fallback DAG nodes", () => {
    const llmGen = createLLMDAGGenerator()
    const dag = llmGen.generateFallbackDAG("validate user input", SAMPLE_CAPABILITIES)

    expect(dag.nodes.length).toBeGreaterThan(0)
    expect(dag.nodes.length).toBeLessThanOrEqual(5)
    expect(dag.metadata.goal).toBe("validate user input")
    expect(dag.metadata.strategy).toBe("STAGED")
  })

  test("LLMDAGGenerator generateFallbackDAG has complete node structure", () => {
    const llmGen = new LLMDAGGenerator()
    const dag = llmGen.generateFallbackDAG("setup CI pipeline", SAMPLE_CAPABILITIES)

    expect(dag.nodes.length).toBeGreaterThan(0)
    expect(dag.edges.length).toBe(dag.nodes.length - 1)

    // Validate each node can be used by taskdag
    for (const node of dag.nodes) {
      const taskNode: DAGNode = {
        node_id: node.node_id,
        capability_id: node.capability_id,
        inputs: node.inputs,
        dependencies: node.dependencies,
        risk_level: node.risk_level,
        estimated_tokens: node.estimated_tokens,
        estimated_duration_ms: node.estimated_duration_ms,
        status: node.status as "pending",
      }
      expect(taskNode.node_id).toBeDefined()
    }
  })

  test("replan preserves replan_count in metadata", () => {
    const dag = createValidLinearDAG()

    let taskDAG = markNodeFailed(dag, "n2")
    const replacement = createReplacementNodes("n1", "rep", 1)
    taskDAG = replaceSubtree(taskDAG, "n2", replacement)

    expect(taskDAG.metadata).toBeDefined()
    expect(taskDAG.metadata!.replan_count).toBe(1)
  })

  test("DAG with cycle is rejected by validateDAG", () => {
    const cyclic: DAG = {
      version: 1,
      nodes: [
        {
          node_id: "n1",
          capability_id: "read_file",
          inputs: {},
          dependencies: ["n3"],
          risk_level: 0,
          estimated_tokens: 100,
          estimated_duration_ms: 5000,
          status: "pending",
        },
        {
          node_id: "n2",
          capability_id: "analyze_code",
          inputs: {},
          dependencies: ["n1"],
          risk_level: 0,
          estimated_tokens: 100,
          estimated_duration_ms: 5000,
          status: "pending",
        },
        {
          node_id: "n3",
          capability_id: "write_file",
          inputs: {},
          dependencies: ["n2"],
          risk_level: 1,
          estimated_tokens: 100,
          estimated_duration_ms: 5000,
          status: "pending",
        },
      ],
      edges: [
        ["n1", "n2"],
        ["n2", "n3"],
        ["n3", "n1"],
      ],
      metadata: {
        goal: "cyclic test",
        strategy: "BAD",
        replan_count: 0,
        created_at: Date.now(),
      },
    }

    const result = validateDAG(cyclic)
    expect(result.valid).toBe(false)
    expect(result.error).toBe("CYCLE_DETECTED")
    expect(result.cycleNodes).toBeDefined()
    expect(result.cycleNodes!.length).toBeGreaterThan(0)
  })

  test("DAG with unknown dependency references is rejected", () => {
    const orphan: DAG = {
      version: 1,
      nodes: [
        {
          node_id: "n1",
          capability_id: "read_file",
          inputs: {},
          dependencies: ["nonexistent"],
          risk_level: 0,
          estimated_tokens: 100,
          estimated_duration_ms: 5000,
          status: "pending",
        },
      ],
      edges: [],
      metadata: {
        goal: "orphan test",
        strategy: "BAD",
        replan_count: 0,
        created_at: Date.now(),
      },
    }

    const result = validateDAG(orphan)
    expect(result.valid).toBe(false)
    expect(result.error).toContain("UNKNOWN_DEPENDENCY")
  })
})
